### ISSUE TITLE
incorrect line number and file for exceptions

### ISSUE THREAD

**Issue by andrewluetgers** [twolfson/node-jsmin-sourcemap#1]
I'm getting the end of the last file as the source of all my exceptions.

**Comment by andrewluetgers** [comment]
Actually this is happening in conjunction with grunt-jsmin-sourcemap, I'm not sure which project is appropriate for this bug.

**Comment by andrewluetgers** [comment]
my project folder structure looks like this

```
project
    dist
        js
    src
        js
    index.html
    grunt.js
```

my config looks like

```
"jsmin-sourcemap": {
    all: {
        src: ["<jsbanner>",
                    "src/js/app.js", "src/js/utils/**.js",
                    "src/js/models/**.js", "src/js/views/**.js", "src/js/collections/**.js",
                    "src/js/widgets/**.js", "src/js/controllers/**.js"
        ],
        dest: "dist/js/<%= pkg.name %>-<%= pkg.version %>-min.js",
        destMap: "dist/js/<%= pkg.name %>-<%= pkg.version %>.js.map",
        srcRoot: "../.."
    }
},
```

**Comment by twolfson** [comment]
Yep, this should be the proper repo. I will try to get to this tonight.

In other news, you are using `**` improperly -- it needs to be in the path not on the file.

```
src/js/models/**/*.js
```

Vague notes on that: https://github.com/isaacs/minimatch#comparisons-to-other-fnmatchglob-implementations

Repo that proves it: https://gist.github.com/3999027

**Comment by twolfson** [comment]
Hey Andrew,
    I wrote tests in attempt to reproduce your issue but everything says it should be working. Is `<jsbanner>` pointing to a file? If not, that might be causing JSMin to act funny since it expects files.
- Todd

**Comment by andrewluetgers** [comment]
ahh that would explain alot, it is actually just a string.

**Comment by andrewluetgers** [comment]
hmm, so I simplified down to the bare minimum and about 50% of my line numbers are correct the others seem to be the correct file but totally wrong line.

```
module.exports = function(grunt) {

    grunt.loadNpmTasks('grunt-rm');
    grunt.loadNpmTasks("grunt-jsmin-sourcemap");

    grunt.initConfig({

        pkg: "<json:package.json>",

        rm: {
            js: 'dist/js/*.js'
        },

        "jsmin-sourcemap": {
            all: {
                src: [
                    "src/js/app.js", "src/js/utils/*.js",
                    "src/js/models/*.js", "src/js/views/*.js", "src/js/collections/*.js",
                    "src/js/widgets/*.js", "src/js/controllers/*.js"
                ],
                dest: "dist/js/<%= pkg.name %>-<%= pkg.version %>-min.js",
                destMap: "dist/js/<%= pkg.name %>-<%= pkg.version %>-min.js.map",
                srcRoot: "../.."
            }
        }
    });

    grunt.registerTask("default", "rm jsmin-sourcemap");

};
```

**Comment by twolfson** [comment]
Damn, that is really weird. The test that I created for your use case is passing:

https://github.com/twolfson/node-jsmin-sourcemap/blob/master/tests/jsmin.sourcemap.tests.json#L32-40

 Alright, tangential info to gather:
- Are you on the latest of `grunt-jsmin-sourcemap` and `node-jsmin-sourcemap`? They should be `1.5.6` and `0.12.2` respectively. You can find this via `npm ls` in your repo library.
- When you say line numbers don't line up, is this for a syntax error or a run time error?
- If you clone each of the repos (and `npm install`), do their respective `npm test`s work?
- What platform are you on? (Windows, Mac, Linux, Other)

P.S. Your `rm` task will not remove the `.map` file -- you can either create a separate task or use `dist/js/*.{js,map}`. See "set" under https://github.com/isaacs/minimatch#properties

**Comment by andrewluetgers** [comment]
OK I was on old versions so I reinstalled both and everything works now, thanks for the reminder to check that :-)
The line numbers I was speaking of were for console.log calls.

**Comment by twolfson** [comment]
Awesome =D
